### ISSUE TITLE
sleep threads

### ISSUE THREAD

**Issue by digitalspaceport** [Nithanim/fancontrol4msi#1]
The sleep thread may need to be increased to 3500. I was running a Celeron on my msi and it was very slow to load the panel.

**Comment by Nithanim** [comment]
I completely agree with you that the sleeptimes are not the best. However I chose come arbitrary values and It worked for me. Since I have a pretty fast computer this is no problem for me (I involuntarily tried with 1ms and it still worked).
Since this can already read ini files i think i will add a config for the sleep time today.
